name: akali
description: An illustration site (booru) server
version: 0.0.2

authors:
  - Rynco Li <lynzrand@outlook.com>
  - Chaos Lun
  - ztl

dependencies:
  # rpc: any
  aqueduct: ^3.1.0
  yaml: ^2.1.15
  ulid: ^1.0.1
  mongo_dart: ^0.3.4
  isolate: ^2.0.2
  crypto: ^2.0.6

dev_dependencies:
  test: any
  aqueduct_test: any
  vm_service_lib: ^0.3.10
  vm_service_client: ^0.2.6

executables:
  akali: main
