name: akali
description: An illustration site (booru) server
version: 0.0.1

authors:
  - Rynco Li <lynzrand@outlook.com>
  - Chaos Lun
  - ztl

dependencies:
  # rpc: any
  aqueduct: any
  yaml: ^2.1.15
  ulid: any
  mongo_dart: ^0.3.3
  isolate: ^2.0.2
  crypto: ^2.0.6

  # dev_dependencies:
  vm_service_lib: ^0.3.10
  vm_service_client: ^0.2.6

executables:
  akali: main
